<!DOCTYPE html>
<html>
<head>
    <title>Blog</title>
    <meta charset="utf8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <a href="index.php"><h1>  Mon Blog</h1></a>
        <nav><a href="admin.php"><i class="fas fa-cogs"></i> Admin</a></nav>
    </header>
    <main>
<?php  include ($template) ?>
    </main>

    <footer><hr>
        le blog@blog2019

    </footer>
</body>
</html>